rule "Types de docs à books"
    when
      "dc"."type" equals "1886:Livre"
    then  
       set "books" in "discovery"."resourceType"
end

rule "Types de docs images"
    when
      "dc"."type" equals "1886:Image"
    then  
       set "images" in "discovery"."resourceType"
end

rule "Types de docs cartes"
    when
      "dc"."type" equals "1886:Carte"
    then  
       set "maps" in "discovery"."resourceType"
end

rule "Types de docs journal"
    when
      "dc"."type" equals "1886:Journal"
    then  
       set "journals" in "discovery"."resourceType"
end

rule "Affichage Auteurs Brief Display"
  when
    exist "dc"."creator"
  then
    copy "dc"."creator" to "discovery"."local1"
end

rule "Affichage Editeur Brief Display"
  when
    exist "dc"."publisher"
  then
    set TEMP"1" to dc value "dc"."publisher"
    add suffix (TEMP"1"," : ")
    set "discovery"."local2" to TEMP"1"
end

