rule "Primo VE - Lds52"
priority 10
	when
		MARC."260" has any "a,b" AND
		MARC."260".ind"1"  equals "3"
	then
	    set TEMP"1" to MARC."260" subfields "b" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
	    remove string (TEMP"1","<<")
        remove string (TEMP"1",">>")
        remove string (TEMP"1","\\(")
        remove string (TEMP"1","\\)")
        remove string (TEMP"1","\\[")
        remove string (TEMP"1","\\]")
        remove leading and trailing spaces (TEMP"1")
        replace spaces (TEMP"1"," ")
        add suffix (TEMP"1"," : ")
	    set pnx."display"."lds52" to TEMP"1"
end

rule "Primo VE - Lds52/2"
priority 20
	when
		MARC."264" has any "a,b" AND
		MARC."264".ind"1"  equals "3" AND
		MARC."264".ind"2"  equals "1"
	then
	    set TEMP"1" to MARC."264" subfields "b" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
	    remove string (TEMP"1","<<")
        remove string (TEMP"1",">>")
        remove string (TEMP"1","\\(")
        remove string (TEMP"1","\\)")
        remove string (TEMP"1","\\[")
        remove string (TEMP"1","\\]")
        remove leading and trailing spaces (TEMP"1")
        replace spaces (TEMP"1"," ")
        add suffix (TEMP"1"," : ")
		set pnx."display"."lds52" to TEMP"1"
end

rule "Primo VE - Lds52/3"
priority 30
	when
		MARC."260" has any "a,b"
	then
	    set TEMP"1" to MARC."260" subfields "b" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
	    remove string (TEMP"1","<<")
        remove string (TEMP"1",">>")
        remove string (TEMP"1","\\(")
        remove string (TEMP"1","\\)")
        remove string (TEMP"1","\\[")
        remove string (TEMP"1","\\]")
        remove leading and trailing spaces (TEMP"1")
        replace spaces (TEMP"1"," ")
        add suffix (TEMP"1"," : ")
		set pnx."display"."lds52" to TEMP"1"
end

rule "Primo VE - Lds52/4"
priority 40
	when
		MARC."264" has any "a,b"
	then
	    set TEMP"1" to MARC."264" subfields "b" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
	    remove string (TEMP"1","<<")
        remove string (TEMP"1",">>")
        remove string (TEMP"1","\\(")
        remove string (TEMP"1","\\)")
        remove string (TEMP"1","\\[")
        remove string (TEMP"1","\\]")
        remove leading and trailing spaces (TEMP"1")
        replace spaces (TEMP"1"," ")
        add suffix (TEMP"1"," : ")
		set pnx."display"."lds52" to TEMP"1"
end