rule "Primo VE - Identifier 020"
	when
		MARC is "020"."a"
	then
		set TEMP"1" to MARC "020"."a"
		add prefix (TEMP"1","$$CISBN$$V")
		create pnx."display"."identifier" with TEMP"1"
end

rule "Primo VE - Identifier 022"
	when
		MARC is "022"."a"
	then
		set TEMP"1" to MARC "022"."a"
		add prefix (TEMP"1","$$CISSN$$V")
		create pnx."display"."identifier" with TEMP"1"
end
rule "Primo VE - Identifier 024"
	when
		MARC is "024"."a" AND
		MARC."024".ind"1"  equals "2"
	then
		set TEMP"1" to MARC "024"."a"
		add prefix (TEMP"1","$$CISMN$$V")
		create pnx."display"."identifier" with TEMP"1"
end

rule "Primo VE - Identifier 035"
	when
	     MARC is "035"."a" AND
	     MARC."035"."a" match ".*OCoLC.*"
	then
		set TEMP"1" to MARC "035"."a"
		add prefix (TEMP"1","$$COCLC$$V")
		create pnx."display"."identifier" with TEMP"1"
end

rule "Primo VE Display - Identifier 035 PPN"
	when
		MARC is "035"."a" AND MARC."035"."a" match "^\\(PPN\\).*"
	then
		set TEMP"1" to MARC."035" sub without sort "a"
        replace string by string (TEMP"1","\\(PPN\\)","")
		add prefix (TEMP"1","<a href='https://www.sudoc.fr/")
        add suffix (TEMP"1","'' target='_blank'>")
        set TEMP"2" to MARC."035" sub without sort "a"
        replace string by string (TEMP"2","\\(PPN\\)","")
        concatenate with delimiter (TEMP"1",TEMP"2","")
        add suffix (TEMP"1","</a>")
        add prefix (TEMP"1","$$CPPN$$V")
		create pnx."display"."identifier" with TEMP"1"
end