rule "Primo VE Display - contents 327"
	when
		MARC is "327"."a"
	then
		create pnx."display"."contents" with MARC."327"."a"
end

rule "Primo VE Display - contents 330"
	when
		MARC is "330"."a"
	then
		set TEMP"1" to MARC."330"."a"
		add prefix (TEMP"1","<b>Résumé : </b><br />")
		create pnx."display"."contents" with TEMP"1"
end

rule "Primo VE Display - contents 359 ind1=2"
	when
		MARC."359" has any "b,c,d,e,f,g,h,i,p,v"
	then
		set TEMP"1" to MARC."359" sub without sort "b,c,d,e,f,g,h,i,p,v" wrap subfields
		add prefix (TEMP"1","<b>Table des matières : </b><br />")
		replace wrapping delimiters (TEMP"1","b","<span class='toc1'>","</span>")
		replace wrapping delimiters (TEMP"1","c","<span class='toc2'>","</span>")
		replace wrapping delimiters (TEMP"1","d","<span class='toc3'>","</span>")
		replace wrapping delimiters (TEMP"1","e","<span class='toc4'>","</span>")
		replace wrapping delimiters (TEMP"1","f","<span class='toc5'>","</span>")
		replace wrapping delimiters (TEMP"1","g","<span class='toc6'>","</span>")
		replace wrapping delimiters (TEMP"1","h","<span class='toc7'>","</span>")
		replace wrapping delimiters (TEMP"1","i","<span class='toc8'>","</span>")
		replace wrapping delimiters (TEMP"1","p","<span class='page'>","</span>")
		replace wrapping delimiters (TEMP"1","v","<span class='vol'>","</span>")
		create pnx."display"."contents" with TEMP"1"
end