rule "Primo VE - Lds02"
priority 90
// Editeur pour affichage dans la brief result
	when
	    MARC."210" has any "c,r,s" AND NOT
		MARC."210".ind"1" equals "1"  
		AND NOT (MARC is "105"."a" AND MARC."105"."a" match "^.{3,8}[m7].*")
	then
		set TEMP"1" to MARC "210" subfields "c,r,s" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"	
		add suffix (TEMP"1"," : ")
		set pnx."display"."lds02" to TEMP"1"  
end

rule "Primo VE - Lds02/2"
priority 80
// Editeur pour affichage dans la brief result
	when
	    MARC."210" has any "c,r,s" AND
		MARC."210".ind"1" equals "1"  
		AND NOT (MARC is "105"."a" AND MARC."105"."a" match "^.{3,8}[m7].*")
	then
		set TEMP"1" to MARC "210" subfields "c,r,s" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"	
		add suffix (TEMP"1"," : ")
		set pnx."display"."lds02" to TEMP"1"  
end

rule "Primo VE - Lds02/3"
priority 70
// Editeur pour affichage dans la brief result
	when
	    MARC."214" has any "c,r,s" AND 
		MARC."214".ind"1" equals " "  
		AND NOT (MARC is "105"."a" AND MARC."105"."a" match "^.{3,8}[m7].*")
	then
		set TEMP"1" to MARC "214" subfields "c,r,s" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
		add suffix (TEMP"1"," : ")
		set pnx."display"."lds02" to TEMP"1"  
end

rule "Primo VE - Lds02/4"
priority 60
// Editeur pour affichage dans la brief result
	when
	    MARC."214" has any "c,r,s" AND 
		MARC."214".ind"2" equals "0"  
		AND NOT (MARC is "105"."a" AND MARC."105"."a" match "^.{3,8}[m7].*")
	then
		set TEMP"1" to MARC "214" subfields "c,r,s" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
		add suffix (TEMP"1"," : ")
		set pnx."display"."lds02" to TEMP"1"  
end

rule "Primo VE - Lds02/5"
priority 50
// Editeur pour affichage dans la brief result
	when
	    MARC."214" has any "c,r,s" AND 
		MARC."214".ind"1" equals "1"  
		AND NOT (MARC is "105"."a" AND MARC."105"."a" match "^.{3,8}[m7].*")
	then
		set TEMP"1" to MARC "214" subfields "c,r,s" delimited by ", " remove substring using regex "(/|:|;|=|,)+$"
		add suffix (TEMP"1"," : ")
		set pnx."display"."lds02" to TEMP"1"  
end

rule "Primo VE - Lds02/6 note de thèse"
priority 50
// Editeur pour affichage dans la brief result
	when
	    MARC."328" has any "b,c,e" AND 
		(MARC is "105"."a" AND MARC."105"."a" match "^.{3,8}[m7].*")
	then
		set TEMP"1" to MARC "328" subfields "b,c,e" delimited by " - " remove substring using regex "(/|:|;|=|,)+$"
		add suffix (TEMP"1"," - ")
		set pnx."display"."lds02" to TEMP"1"  
end