rule "Primo VE - Lds57"
	when
		Latin display MARC."206" has any "a,b,c,d"
	then
		hen
		set TEMP"1" to MARC."206" sub without sort "a,b,c,d" wrap subfields
		replace wrapping delimiters (TEMP"1","a","","")
      	replace wrapping delimiters (TEMP"1","b","","")
      	replace wrapping delimiters (TEMP"1","c"," ; ","")
		replace wrapping delimiters (TEMP"1","d"," (",")")
		set pnx."display"."lds57" to TEMP"1"
end