rule "Primo VE - Lds54"
	when
		MARC is "410"."1"
	then
		set TEMP"1" to MARC."410"."1"
		remove string (TEMP"1","^001\\(PPN\\)")
		create pnx."display"."lds54" with TEMP"1"
end

rule "Primo VE - Lds54 ISSN Collections Unimarc 410"
	when
		MARC is "410"."x"
	then
		create pnx."display"."lds54" with MARC "410"."x"

end

rule "Primo VE - Lds54 TITRE collections Unimarc 410"
	when
		MARC is "410"."t"
	then
		set TEMP"1" to MARC."410"."t"
		remove string (TEMP"1","<<")
		remove string (TEMP"1",">>")
		create pnx."display"."lds54" with TEMP"1"
end

rule "Primo VE - Lds54 ISSN Collections 225"
	when
		MARC is "225"."x"
		AND NOT MARC is "410"
	then
		create pnx."display"."lds54" with MARC "225"."x"

end

rule "Primo VE - Lds54 TITRE collections 225"
	when
		MARC is "225"."a"
		AND NOT MARC is "410"
	then
		set TEMP"1" to MARC."225"."a"
		remove string (TEMP"1","<<")
		remove string (TEMP"1",">>")
		create pnx."display"."lds54" with TEMP"1"
end

rule "Primo VE Display - Lds54 ISBN notice unimarc"
	when
		MARC is "010"."a"
	then
		create pnx."display"."lds54" with MARC "010"."a"

end

rule "Primo VE Display - Lds54 ISSN notice unimarc"
	when
		MARC is "011"."a"
	then
		create pnx."display"."lds54" with MARC "011"."a"

end

rule "Primo VE Display - Lds54 PPN notice unimarc"
	when
		MARC is "035"."a" AND MARC."035"."a" match "^\\(PPN\\).*"
	then
		set TEMP"1" to MARC."035" sub without sort "a"
        replace string by string (TEMP"1","\\(PPN\\)","")
		create pnx."display"."lds54" with TEMP"1"
end

rule "Primo VE Display - Lsr54 titre notice unimarc"
    when
		MARC is "200"."a"
	then
		set TEMP"1" to MARC."200"."a"
		remove string (TEMP"1","<<")
		remove string (TEMP"1",">>")
		create pnx."display"."lds54" with TEMP"1"
end
