rule "Primo VE UNIMARC - Lsr56"
	when
		MARC is "214"."c"
	then
		set TEMP"1" to MARC."214"."c"
		remove leading and trailing spaces (TEMP"1")
		remove substring using regex (TEMP"1","^(/|:|;|=|,)+")
		remove leading and trailing spaces (TEMP"1")
		replace spaces (TEMP"1"," ")
	    remove string (TEMP"1","<<")
        remove string (TEMP"1",">>")
        remove string (TEMP"1","\\(")
        remove string (TEMP"1","\\)")
        remove string (TEMP"1","\\[")
        remove string (TEMP"1","\\]")
        remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
		create pnx."search"."lsr56" with TEMP"1"
end

rule "Primo VE UNIMARC - Lsr56 Editeur 210$c"
	when
		MARC is "210"."c"
	then
		set TEMP"1" to MARC."210"."c"
		remove leading and trailing spaces (TEMP"1")
		remove substring using regex (TEMP"1","^(/|:|;|=|,)+")
		remove leading and trailing spaces (TEMP"1")
		replace spaces (TEMP"1"," ")
	    remove string (TEMP"1","<<")
        remove string (TEMP"1",">>")
        remove string (TEMP"1","\\(")
        remove string (TEMP"1","\\)")
        remove string (TEMP"1","\\[")
        remove string (TEMP"1","\\]")
        remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
		create pnx."search"."lsr56" with TEMP"1"
end
